/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#dee5ff",
        "surface-variant": "#192540",
        "on-secondary-fixed": "#00452d",
        surface: "#060e20",
        "primary-dim": "#6063ee",
        "secondary-fixed": "#69f6b8",
        "error-container": "#a70138",
        "inverse-surface": "#faf8ff",
        "surface-tint": "#a3a6ff",
        "secondary-dim": "#58e7ab",
        "on-error": "#490013",
        "surface-container-low": "#091328",
        "on-tertiary-container": "#4a2c00",
        "on-secondary": "#005a3c",
        "on-tertiary": "#573500",
        "on-secondary-container": "#e1ffec",
        "surface-container": "#0f1930",
        "tertiary-fixed-dim": "#e79400",
        "surface-dim": "#060e20",
        tertiary: "#ffb148",
        error: "#ff6e84",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-lowest": "#000000",
        "surface-container-highest": "#192540",
        "on-primary-fixed-variant": "#0e009d",
        "surface-container-high": "#141f38",
        "primary-container": "#9396ff",
        "on-tertiary-fixed-variant": "#563400",
        background: "#060e20",
        "on-secondary-fixed-variant": "#006544",
        "inverse-on-surface": "#4d556b",
        "outline-variant": "#40485d",
        "primary-fixed-dim": "#8387ff",
        "tertiary-fixed": "#f8a010",
        "secondary-container": "#006c49",
        "on-surface-variant": "#a3aac4",
        "surface-bright": "#1f2b49",
        secondary: "#69f6b8",
        "primary-fixed": "#9396ff",
        "on-primary-container": "#0a0081",
        "tertiary-dim": "#e79400",
        "on-primary": "#0f00a4",
        "inverse-primary": "#494bd7",
        "error-dim": "#d73357",
        primary: "#a3a6ff",
        "secondary-fixed-dim": "#58e7ab",
        outline: "#6d758c",
        "on-surface": "#dee5ff",
        "on-primary-fixed": "#000000",
        "tertiary-container": "#f8a010",
        "on-error-container": "#ffb2b9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Montserrat", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
